project:
  type: website
  output-dir: _site

website:
  title: "Dividing the Atom Primordially"
  navbar: false
  sidebar: false

format:
  html:
    theme: none
    css: styles.css
    page-layout: full
